#include "main.h"
#include "sfm_4100.h"
#include <string.h>

// Peripheral handles as generated by Cube
I2C_HandleTypeDef hi2c1;
TIM_HandleTypeDef htim3;
UART_HandleTypeDef huart1;
UART_HandleTypeDef huart2;

// Functions generated by Cube
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_TIM3_Init(void);

// USART1 global interrupt hanlder
void USART1_IRQHandler(void);
// TIM3 interrupt handler
void TIM3_IRQHandler(void);

// SFM4100 API
uint8_t sfm4100_get_eeprom_base_address(uint16_t *p_address);
uint8_t sfm4100_read_register(uint8_t reg, uint16_t *p_reg_value);
uint8_t sfm4100_write_register(uint8_t reg, uint16_t *p_reg_value);
uint8_t sfm4100_read_serial_number(uint32_t *p_serial_number);
uint8_t sfm4100_read_scale_factor(uint16_t *p_scale_factor);
uint8_t sfm4100_read_flow_unit(char *flow_unit); // may be 11 bytes
uint8_t sfm4100_soft_reset();

// Sensiron SFM4100 address is actually 0x01 shifted to the left by 1 bit
#define SENSORON_ADDR		(0x01 << 1)

/**
 * SFM4100 user commands list
 * Each SFM4100 command returns or expects 2 bytes with the exception of the last 3
 */
uint8_t user_reg_w = 0xe2;	// 16 bits
uint8_t user_reg_r = 0xe3; // 16 bits
uint8_t adv_user_reg_w = 0xe4; // 16 bits
uint8_t adv_user_reg_r = 0xe5; // 16 bits
uint8_t read_only_reg1_r = 0xe7;
uint8_t read_only_reg2_r = 0xe9;
uint8_t trigger_flow_measurement = 0xf1;
uint8_t trigger_temp_measurement = 0xf3;
uint8_t trigger_vdd_measurement = 0xf5; // Not implemented on SFM4100
uint8_t eeprom_w = 0xfa;
uint8_t eeprom_r = 0xfa;
uint8_t soft_reset = 0xfe;

// SF04 eeprom map
#define EE_ADR_SN_CHIP 0x02E4		//
#define EE_ADR_SN_PRODUCT 0x02F8	//
#define EE_ADR_SCALE_FACTOR 0x02B6
#define EE_ADR_FLOW_UNIT 0x02B7

// Receive buffer
uint8_t receive_buffer[32] = { 0 };

// Temp value
uint16_t reg_value = 0;

int main(void) {

	// Initialize peripherals
	HAL_Init();
	SystemClock_Config();
	MX_GPIO_Init();
	MX_I2C1_Init();
	MX_TIM3_Init();
	MX_USART2_UART_Init();
	MX_USART1_UART_Init();

	// Get chip serial number
	// Get product serial number
	// Get scale factor
	// Get flow unit


	sfm4100_soft_reset();										// Issue soft reset
	sfm4100_read_register(adv_user_reg_r, &reg_value); 			// Change flow resolution to 16 bits
	reg_value |= 0xe00;
	sfm4100_write_register(adv_user_reg_w, &reg_value);

	while (1) {
		HAL_Delay(250);
		HAL_GPIO_TogglePin(LD3_GPIO_Port, LD3_Pin);

		// Read all registers
		//sfm4100_read_register(user_reg_r, &reg_value);
		//sfm4100_read_register(adv_user_reg_r, &reg_value);
		//sfm4100_read_register(read_only_reg1_r, &reg_value);
		//sfm4100_read_register(read_only_reg2_r, &reg_value);

		// Trigger flow measurement
		sfm4100_read_register(trigger_flow_measurement, &reg_value);
		sfm4100_read_register(trigger_temp_measurement, &reg_value);

		// @TODO Read serial number

		// @TODO USART1 IRQ routine - need interrupt on receive
		/* Put every received char in a buffer and start the timer.
		 * If the timer expires, a frame is received. Raise a flag to be polled in main */
	}

}

/**
 * @brief System Clock Configuration
 * @retval None
 */
void SystemClock_Config(void) {
	RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
	RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };
	RCC_PeriphCLKInitTypeDef PeriphClkInit = { 0 };

	/** Initializes the CPU, AHB and APB busses clocks
	 */
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI
			| RCC_OSCILLATORTYPE_HSE;
	RCC_OscInitStruct.HSEState = RCC_HSE_BYPASS;
	RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
	RCC_OscInitStruct.HSIState = RCC_HSI_ON;
	RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
	RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
	RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
		Error_Handler();
	}
	/** Initializes the CPU, AHB and APB busses clocks
	 */
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
			| RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
		Error_Handler();
	}
	PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART1
			| RCC_PERIPHCLK_I2C1;
	PeriphClkInit.Usart1ClockSelection = RCC_USART1CLKSOURCE_PCLK1;
	PeriphClkInit.I2c1ClockSelection = RCC_I2C1CLKSOURCE_HSI;
	if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK) {
		Error_Handler();
	}
}

/**
 * @brief I2C1 Initialization Function
 * @param None
 * @retval None
 */
static void MX_I2C1_Init(void) {
	hi2c1.Instance = I2C1;
	hi2c1.Init.Timing = 0x00201D2B;
	hi2c1.Init.OwnAddress1 = 0;
	hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
	hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
	hi2c1.Init.OwnAddress2 = 0;
	hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
	hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
	hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
	if (HAL_I2C_Init(&hi2c1) != HAL_OK) {
		Error_Handler();
	}
	/** Configure Analogue filter
	 */
	if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE)
			!= HAL_OK) {
		Error_Handler();
	}
	/** Configure Digital filter
	 */
	if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK) {
		Error_Handler();
	}
}

/**
 * @brief USART2 Initialization Function
 * @param None
 * @retval None
 */
static void MX_USART2_UART_Init(void) {

	huart2.Instance = USART2;
	huart2.Init.BaudRate = 9600;
	huart2.Init.WordLength = UART_WORDLENGTH_8B;
	huart2.Init.StopBits = UART_STOPBITS_1;
	huart2.Init.Parity = UART_PARITY_NONE;
	huart2.Init.Mode = UART_MODE_TX_RX;
	huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart2.Init.OverSampling = UART_OVERSAMPLING_16;
	huart2.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
	huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
	if (HAL_UART_Init(&huart2) != HAL_OK) {
		Error_Handler();
	}

}

/**
 * @brief USART1 Initialization Function
 * @param None
 * @retval None
 */
static void MX_USART1_UART_Init(void) {
	huart1.Instance = USART1;
	huart1.Init.BaudRate = 9600;
	huart1.Init.WordLength = UART_WORDLENGTH_8B;
	huart1.Init.StopBits = UART_STOPBITS_2;
	huart1.Init.Parity = UART_PARITY_NONE;
	huart1.Init.Mode = UART_MODE_TX_RX;
	huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart1.Init.OverSampling = UART_OVERSAMPLING_16;
	huart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
	huart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;

	// Set interrupt priority & enable interrupts
	HAL_NVIC_SetPriority(USART1_IRQn, 5, 5);
	HAL_NVIC_EnableIRQ(USART1_IRQn);

	if (HAL_RS485Ex_Init(&huart1, UART_DE_POLARITY_HIGH, 0, 0) != HAL_OK) {
		Error_Handler();
	}
}

/**
 * @brief GPIO Initialization Function
 * @param None
 * @retval None
 */
static void MX_GPIO_Init(void) {
	GPIO_InitTypeDef GPIO_InitStruct = { 0 };

	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOF_CLK_ENABLE();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();

	/*Configure GPIO pin Output Level */
	HAL_GPIO_WritePin(LD3_GPIO_Port, LD3_Pin, GPIO_PIN_RESET);

	/*Configure GPIO pin : LD3_Pin */
	GPIO_InitStruct.Pin = LD3_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(LD3_GPIO_Port, &GPIO_InitStruct);

}

/**
 * @brief TIM3 Initialization Function
 * @param None
 * @retval None
 */
static void MX_TIM3_Init(void) {

	/* USER CODE BEGIN TIM3_Init 0 */

	/* USER CODE END TIM3_Init 0 */

	TIM_ClockConfigTypeDef sClockSourceConfig = { 0 };
	TIM_MasterConfigTypeDef sMasterConfig = { 0 };

	/* USER CODE BEGIN TIM3_Init 1 */

	/* USER CODE END TIM3_Init 1 */
	htim3.Instance = TIM3;
	htim3.Init.Prescaler = 8;
	htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
	htim3.Init.Period = 36090;
	htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
	htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
	if (HAL_TIM_Base_Init(&htim3) != HAL_OK) {
		Error_Handler();
	}
	sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
	if (HAL_TIM_ConfigClockSource(&htim3, &sClockSourceConfig) != HAL_OK) {
		Error_Handler();
	}
	sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
	sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
	if (HAL_TIMEx_MasterConfigSynchronization(&htim3, &sMasterConfig)
			!= HAL_OK) {
		Error_Handler();
	}
	/* USER CODE BEGIN TIM3_Init 2 */
	HAL_NVIC_SetPriority(TIM3_IRQn, 5, 5);
	HAL_NVIC_EnableIRQ(TIM3_IRQn);
	/* USER CODE END TIM3_Init 2 */

}

void USART1_IRQHandler(void) {
	if (__HAL_UART_GET_FLAG(&huart1, USART_ISR_TXE)) {
		// Hanlde transmit interrupt
	} else if (__HAL_UART_GET_FLAG(&huart1, USART_ISR_RXNE)) {
		// Handle receive interrupt
		// Clear flag
		char ch = USART1->RDR;
		// Reset timer
	}
}

void TIM3_IRQHandler(void) {
	// @TODO: Clear interrupt flag, toggle pin to confirm timing
}

uint8_t sfm4100_get_eeprom_base_address(uint16_t *p_address) {
	// Read read-only register 2
	if (HAL_I2C_Master_Transmit(&hi2c1, SENSORON_ADDR, &read_only_reg2_r, 0x01,
			100) != HAL_OK) {
		Error_Handler();
		return 0;
	}

	if (HAL_I2C_Master_Receive(&hi2c1, SENSORON_ADDR, receive_buffer, 0x03, 100)
			!= HAL_OK) {
		Error_Handler();
		return 0;
	}

	// Copy data from receive buffer. Note that MSB is at position [0]
	/**
	 * The EEPROM address is composed of an EEPROM base address and an address offset.
	 * To determine the base EEPROM address for general sensor information,
	 * bit <2:0> of Read-Only Register 2 (called active configuration field at boot time)
	 * must be multiplied by h300.
	 * Then the Wordadr Offset of following table must be added to that address.
	 * See Application Note for I2C Flow and Differential Pressure Sensors
	 */
	uint16_t read_only_reg2_contents = 0;
	read_only_reg2_contents |= (uint16_t) (receive_buffer[0] << 8);
	read_only_reg2_contents |= (uint16_t) (receive_buffer[1]);
	read_only_reg2_contents &= 0x07; 	// Mask bits [2:0]
	read_only_reg2_contents *= 0x300;

	*p_address = read_only_reg2_contents;
}

uint8_t sfm4100_read_register(uint8_t reg, uint16_t *p_reg_value) {
	// Issue write command
	if (HAL_I2C_Master_Transmit(&hi2c1, SENSORON_ADDR, &reg, 0x01, 100)
			!= HAL_OK) {
		Error_Handler();
		return 0;
	}

	// Read contents of register
	if (HAL_I2C_Master_Receive(&hi2c1, SENSORON_ADDR, receive_buffer, 0x03, 100)
			!= HAL_OK) {
		Error_Handler();
		return 0;
	}

	uint16_t reg_contents = 0;
	reg_contents |= (uint16_t) (receive_buffer[0] << 8);
	reg_contents |= (uint16_t) (receive_buffer[1]);

	*p_reg_value = reg_contents;

	return 1;
}

uint8_t sfm4100_write_register(uint8_t reg, uint16_t *p_reg_value) {
	// A write to a register will be 2 bytes only. Need to concatenate address and reg value
	// Total transfer length: 3 bytes
	uint16_t reg_value = *p_reg_value;
	uint8_t data[3] = { 0 };
	data[0] = reg;
	data[1] = (uint8_t) (reg_value >> 8);
	data[2] = (uint8_t) (reg_value & 0xff);

	// Issue write command
	if (HAL_I2C_Master_Transmit(&hi2c1, SENSORON_ADDR, data, 0x04, 100)
			!= HAL_OK) {
		Error_Handler();
		return 0;
	}
}

uint8_t sfm4100_read_serial_number(uint32_t *p_serial_number) {
	// @TODO Implement
}

uint8_t sfm4100_read_scale_factor(uint16_t *p_scale_factor) {
	// @TODO Implement
}

uint8_t sfm4100_read_flow_unit(char *flow_unit) {
	// @TODO Implement
}

uint8_t sfm4100_soft_reset() {
	// Issue write command
	// @TODO - check if it's working
	if (HAL_I2C_Master_Transmit(&hi2c1, SENSORON_ADDR, &soft_reset, 0x01, 100)
			!= HAL_OK) {
		Error_Handler();
		return 0;
	}
	return 1;
}

/**
 * @brief  Period elapsed callback in non blocking mode
 * @note   This function is called  when TIM2 interrupt took place, inside
 * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
 * a global variable "uwTick" used as application time base.
 * @param  htim : TIM handle
 * @retval None
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
	/* USER CODE BEGIN Callback 0 */

	/* USER CODE END Callback 0 */
	if (htim->Instance == TIM2) {
		HAL_IncTick();
	}
	/* USER CODE BEGIN Callback 1 */

	/* USER CODE END Callback 1 */
}

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void) {
	/* USER CODE BEGIN Error_Handler_Debug */
	/* User can add his own implementation to report the HAL error return state */

	/* USER CODE END Error_Handler_Debug */
}

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
